project:
  type: book
  output-dir: _book

book:
  title: "Discontinuous Galerkin Finite Element Methods"
  author: "Vikas Sharma"
  date: "1/29/2025"
  reader-mode: true
  search: true
  repo-url: https://github.com/poromechanics/dg-fem/
  site-url: https://poromechanics.github.io/dg-fem
  repo-actions: [edit, issue]
  downloads: [pdf,epub]
  sharing: [twitter, linkedin]
  favicon: ./figures/favicon.png
  cover-image: ./figures/cover.svg
  cover-image-alt: DG FEM
  twitter-card: true
  page-navigation: true
  page-footer: 
    left: "Copyright 2025, Vikas Sharma" 
    right: 
      - icon: github
        href: https://github.com/vickysharma0812
      - icon: twitter
        href: https://twitter.com/vickysharma0812
      - icon: linkedin
        href: https://linkedin.com/in/vickysharma0812
  sidebar:
      style: docked
      background: light
  chapters:
    - index.md
    - intro.md
    - ./dg-in-one-dim.md
    - ./dg-in-multi-dim.md
    # - part: "An outline of the finite element method (1D case)"
    #   chapters:
    #     - ./outline-of-fem/mathematical-model.md
    #     - ./outline-of-fem/conceptualization.md
    #     - ./outline-of-fem/approximate-solution.md
    #     - ./outline-of-fem/general-formulation-oned.md
    #     - ./outline-of-fem/fem-in-oned.md
    - summary.md
    - references.md
  # appendices:
  # crossref:

bibliography: references.bib

comments:
  hypothesis: true

execute:
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - brand
  # pdf:
  #   documentclass: scrreprt



